config/routes.rb
Rails.application.routes.draw do

  patch "/support_requests/:id/mark_done" => "support_requests#mark_done", as: :mark_done_support_request

  get "/support_requests/search" => "support_requests#search", as: :support_requests_search

  resources :support_requests

end

app/models/support_request.rb
class SupportRequest < ActiveRecord::Base

  DEPT_SALES     = "Sales"
  DEPT_MARKETING = "Marketing"
  DEPT_TECHNICAL = "Technical"

  DEPARTMENTS    = [DEPT_SALES, DEPT_MARKETING, DEPT_TECHNICAL]

  after_initialize :set_defaults

  validates :name, presence: true
  validates :email, presence: true

  def self.search(term)
    wildcard_term = "%#{term}%"
    where("name ILIKE :term OR email ILIKE :term OR department ILIKE :term OR message ILIKE :term", {term: wildcard_term})
  end

  private

  def set_defaults
    self.done ||= false
    self.department ||= DEPT_SALES
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/support_requests_controller.rb
class SupportRequestsController < ApplicationController
  def new
    @support_request = SupportRequest.new
  end

  def create
    support_request_params = params.require(:support_request)
                                    .permit(:name, :email, :department, :message)
    @support_request = SupportRequest.new(support_request_params)
    if @support_request.save
      flash[:notice] = "Request Saved!"
      redirect_to support_request_path(@support_request)
    else
      flash[:alert] = "Request not saved"
      render :new
    end
  end

  def show
    @support_request = SupportRequest.find params[:id]
  end

  def index
    @support_requests = SupportRequest.order("done ASC").page(params[:page]).per(7)
    # if params[:q]
    #   @support_requests = SupportRequest.search(params[:q])
    # else
    #   @support_requests = SupportRequest.order("done ASC")
    # end
  end

  def edit
    @support_request = SupportRequest.find params[:id]
  end

  def update
    @support_request = SupportRequest.find params[:id]
    support_request_params = params.require(:support_request)
                                    .permit(:name, :email, :department, :message, :done)
    if @support_request.update(support_request_params)
      if support_request_params.has_key?(:done)
        redirect_to support_requests_path, notice: "Request updated!"
      else
        redirect_to @support_request, notice: "Request updated!"
      end
      # redirect_to update_success_direction(support_request_params, @support_request),
      #             notice: "support request updated!"
    else
      render :edit
    end
  end

  def mark_done
    @support_request = SupportRequest.find params[:id]
    @support_request.done = !@support_request.done
    @support_request.save
    redirect_to support_requests_path
  end

  def search
    @support_requests = SupportRequest.search(params[:q]).page(params[:page]).per(7)
    render :index
  end

  private

  # def update_success_direction(params, support_request)
  #   if support_request.has_key?(:done)
  #     support_requests_path
  #   else
  #     support_request
  #   end
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/support_requests_helper.rb
module SupportRequestsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Supporter</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= form_tag support_requests_search_path, method: :get do %>
  <%= text_field_tag :q, params[:q], placeholder: "Search.." %>
  <%= submit_tag "search" %>
<% end %>

<%= yield %>

</body>
</html>

app/views/support_requests/_form.html.erb
<%= @support_request.errors.full_messages.join(", ") %>
<%= form_for @support_request do |f| %>
  <div>
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <div>
    <%= f.label :email %>
    <%= f.email_field :email %>
  </div>
  <div>
    <%= f.label :department %>
    <%= f.radio_button :department, SupportRequest::DEPT_SALES %> Sales
    <%= f.radio_button :department, SupportRequest::DEPT_MARKETING %> Marketing
    <%= f.radio_button :department, SupportRequest::DEPT_TECHNICAL %> Technical
  </div>
  <div>
    <%= f.label :message %>
    <%= f.text_area :message %>
  </div>
  <%= f.submit %>
<% end %>

app/views/support_requests/edit.html.erb
<h1>Edit Support Request</h1>

<%= render "form" %>

app/views/support_requests/index.html.erb
<h1>All Requests</h1>

<table>
  <tr>
    <td>Name</td>
    <td>Email</td>
    <td>Department</td>
    <td>Message</td>
    <td></td>
  </tr>
  <% @support_requests.each do |req| %>
    <tr>
      <td><%= req.name %></td>
      <td><%= req.email %></td>
      <td><%= req.department %></td>
      <td><%= req.message %></td>
      <td>
        <%= link_to "Edit", edit_support_request_path(req) %>

        <% if req.done? %>
          <%= button_to "Un-Done", support_request_path(req, support_request: {done: false}),
                                method: :patch%>
        <% else %>
        <%= button_to "Done", support_request_path(req, support_request: {done: true}),
                              method: :patch%>
        <% end %>
        <!-- <% if req.done? %>
          <%= button_to "Un-Done", mark_done_support_request_path(req),
                                method: :patch%>
        <% else %>
          <%= button_to "Done", mark_done_support_request_path(req),
                              method: :patch%>
        <% end %> -->
      </td>
    </tr>

  <% end %>
</table>

<%= paginate @support_requests %>

app/views/support_requests/new.html.erb
<h1>New Support Request</h1>

<%= render "form" %>

app/views/support_requests/show.html.erb
<h1><%= @support_request.name %></h1>

<p><%= @support_request.email %></p>

<p>Department: <%= @support_request.department %></p>

<p>Mesage: <%= @support_request.message %></p>